
package com.ejs.client.serviceWSDL.br.com.ejs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://ejs.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param getAllCustomerDetailRequest
     * @return
     *     returns br.com.ejs.GetAllCustomerDetailResponse
     */
    @WebMethod(operationName = "GetAllCustomerDetail")
    @WebResult(name = "GetAllCustomerDetailResponse", targetNamespace = "http://ejs.com.br", partName = "GetAllCustomerDetailResponse")
    public GetAllCustomerDetailResponse getAllCustomerDetail(
        @WebParam(name = "GetAllCustomerDetailRequest", targetNamespace = "http://ejs.com.br", partName = "GetAllCustomerDetailRequest")
        GetAllCustomerDetailRequest getAllCustomerDetailRequest);

    /**
     * 
     * @param deleteCustomerDetailRequest
     * @return
     *     returns br.com.ejs.DeleteCustomerDetailResponse
     */
    @WebMethod(operationName = "DeleteCustomerDetail")
    @WebResult(name = "DeleteCustomerDetailResponse", targetNamespace = "http://ejs.com.br", partName = "DeleteCustomerDetailResponse")
    public DeleteCustomerDetailResponse deleteCustomerDetail(
        @WebParam(name = "DeleteCustomerDetailRequest", targetNamespace = "http://ejs.com.br", partName = "DeleteCustomerDetailRequest")
        DeleteCustomerDetailRequest deleteCustomerDetailRequest);

    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns br.com.ejs.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://ejs.com.br", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://ejs.com.br", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

    /**
     * 
     * @param saveCustomerDetailRequest
     * @return
     *     returns br.com.ejs.SaveCustomerDetailResponse
     */
    @WebMethod(operationName = "SaveCustomerDetail")
    @WebResult(name = "SaveCustomerDetailResponse", targetNamespace = "http://ejs.com.br", partName = "SaveCustomerDetailResponse")
    public SaveCustomerDetailResponse saveCustomerDetail(
        @WebParam(name = "SaveCustomerDetailRequest", targetNamespace = "http://ejs.com.br", partName = "SaveCustomerDetailRequest")
        SaveCustomerDetailRequest saveCustomerDetailRequest);

}
